### PR TITLE
Re-enable open tenant creation in demo stack

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Review by bbranan — APPROVED** [review]

**Comment by mjgiarlo** [comment]
@bbranan Thanks! Now that this has been merged, what steps do we need to take to get the demo instance redeployed w/ the new setting?

**Comment by bbranan** [comment]
@mjgiarlo We'll need to perform an `update-stack` call with Cloudformation to get the new parameter in place. It's on my list, but it may be a day or two before I get to it (lots of things to catch up on.)

**Comment by mjgiarlo** [comment]
no problem. thx!

**Comment by mjgiarlo** [comment]
@scossu, FYI :point_up:

**Comment by scossu** [comment]
Thanks @mjgiarlo @bbranan ! Can you please drop a note here when that is deployed in the demo site?

**Comment by bbranan** [comment]
Will do @scossu

**Comment by mjgiarlo** [comment]
@scossu Open tenant creation is now enabled again. Thanks for your patience!

**Pull request merged**
