### PR TITLE
Update to latest EB solution stacks

### LINKED ISSUE #177: Cannot deploy due to outdated solution stack
It looks like the CloudFormation template uses some Elastic Beanstalk solution stacks that are out of date. I am deploying to the `us-east-1` AWS region, and seeing the following error on deploy:

image

This error occurred under the "Hyku solr stack." Do you have any idea how we can fix this?

Thanks!

### PR DESCRIPTION
**Pull request by cjhowe-us**
This updates all the EB solution stacks. As part of this, there was a problem with the configuration files on the bastion due to the update, so these files are fixed as well. Fixes #177

### CODE REVIEW

**Comment by bbranan** [comment]
@cjhowe7 these changes look good, though it appears that `templates/zookeeper.yaml` could use a similar update to the SolutionStackName. Were you able to get this to deploy without making that change?

**Review by bbranan — CHANGES_REQUESTED** [review]
Please also update the SolutionStackName in `templates/zookeeper.yaml`

**Comment by cjhowe-us** [comment]
We were able to deploy it without that change, but I am testing an update to that solution stack currently.

**Comment by cjhowe-us** [comment]
We have tested this change and it seems to work. Let me know if there's anything else you need!

**Review by bbranan — APPROVED** [review]

**Comment by bbranan** [comment]
Thanks @cjhowe7!

**Pull request merged**
