### PR TITLE
Add rolling deployment policy for webapp updates

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@cbeer WIP or ship?

**Comment by eefahy** [comment]
I'm interested to hear why `RollingWithAdditionalBatch` vs just `Rolling` or even `Immutable`

**Comment by cbeer** [comment]
- Anything is better than what we have now.
-  Although `Immutable` seems like what we want, I'm also nervous that our application isn't ready for it (we already know, for instance, the application is storing the "PID minter" state locally) 
- `RollingWithAdditionalBatch` seems superior to `Rolling`, since it can validate the update without removing nodes from the pool (and may help in a 1-node situation?).

**Comment by eefahy** [comment]
Good enough for me. Hopefully we can resolve the blockers to using `Immutable` in the future.

**Pull request merged**
